databaseChangeLog:
  - changeSet:
      id: 012-ddl-functions-001-fn-set-updated-at
      author: juanPabloGomezPerdomo
      logicalFilePath: 01_ddl/06_functions/001_fn_set_updated_at.sql
      labels: "ddl,functions"
      comment: Runs 01_ddl/06_functions/001_fn_set_updated_at.sql.
      changes:
        - sqlFile:
            path: 001_fn_set_updated_at.sql
            relativeToChangelogFile: true
            splitStatements: false
            endDelimiter: ;
            stripComments: false
      rollback:
        - sqlFile:
            path: ../../05_rollbacks/01_ddl/06_functions/001_fn_set_updated_at.rollback.sql
            relativeToChangelogFile: true
            splitStatements: true
            endDelimiter: ;
            stripComments: false
  - changeSet:
      id: 013-ddl-functions-002-fn-calculate-nights
      author: juanPabloGomezPerdomo
      logicalFilePath: 01_ddl/06_functions/002_fn_calculate_nights.sql
      labels: "ddl,functions"
      comment: Runs 01_ddl/06_functions/002_fn_calculate_nights.sql.
      changes:
        - sqlFile:
            path: 002_fn_calculate_nights.sql
            relativeToChangelogFile: true
            splitStatements: false
            endDelimiter: ;
            stripComments: false
      rollback:
        - sqlFile:
            path: ../../05_rollbacks/01_ddl/06_functions/002_fn_calculate_nights.rollback.sql
            relativeToChangelogFile: true
            splitStatements: true
            endDelimiter: ;
            stripComments: false
  - changeSet:
      id: 014-ddl-functions-003-fn-calculate-total
      author: juanPabloGomezPerdomo
      logicalFilePath: 01_ddl/06_functions/003_fn_calculate_total.sql
      labels: "ddl,functions"
      comment: Runs 01_ddl/06_functions/003_fn_calculate_total.sql.
      changes:
        - sqlFile:
            path: 003_fn_calculate_total.sql
            relativeToChangelogFile: true
            splitStatements: false
            endDelimiter: ;
            stripComments: false
      rollback:
        - sqlFile:
            path: ../../05_rollbacks/01_ddl/06_functions/003_fn_calculate_total.rollback.sql
            relativeToChangelogFile: true
            splitStatements: true
            endDelimiter: ;
            stripComments: false
  - changeSet:
      id: 015-ddl-functions-004-fn-calculate-reservation-price
      author: juanPabloGomezPerdomo
      logicalFilePath: 01_ddl/06_functions/004_fn_calculate_reservation_price.sql
      labels: "ddl,functions"
      comment: Runs 01_ddl/06_functions/004_fn_calculate_reservation_price.sql.
      changes:
        - sqlFile:
            path: 004_fn_calculate_reservation_price.sql
            relativeToChangelogFile: true
            splitStatements: false
            endDelimiter: ;
            stripComments: false
      rollback:
        - sqlFile:
            path: ../../05_rollbacks/01_ddl/06_functions/004_fn_calculate_reservation_price.rollback.sql
            relativeToChangelogFile: true
            splitStatements: true
            endDelimiter: ;
            stripComments: false
  - changeSet:
      id: 016-ddl-functions-005-fn-stock-available
      author: juanPabloGomezPerdomo
      logicalFilePath: 01_ddl/06_functions/005_fn_available_stock.sql
      labels: "ddl,functions"
      comment: Runs 01_ddl/06_functions/005_fn_available_stock.sql.
      changes:
        - sqlFile:
            path: 005_fn_available_stock.sql
            relativeToChangelogFile: true
            splitStatements: false
            endDelimiter: ;
            stripComments: false
      rollback:
        - sqlFile:
            path: ../../05_rollbacks/01_ddl/06_functions/005_fn_available_stock.rollback.sql
            relativeToChangelogFile: true
            splitStatements: true
            endDelimiter: ;
            stripComments: false
